name: emtux actions
description: emtux actions
inputs:
  params:
    description: '引数のJSONオブジェクト'
    required: true
  file:
    description: 'fileの中身'
    required: true
outputs:
  result-message: # outputして他から参照するための名前
    description: '生成した文字列'
runs:
  using: 'docker'
  image: 'Dockerfile'
